import type { Product } from "./products";

export const productsPL: Product[] = [
  {
    slug: "performance",
    name: "Performance",
    fullName: "knowing more. Performance",
    tagline: "Energia · Regeneracja · Skupienie",
    headline: "Dla tych, którzy\nwymagają więcej.",
    description: "Klinicznie dawkowane składniki aktywne dla trwałej wydajności i mierzalnej regeneracji.",
    longDescription:
      "Performance zostało stworzone dla osób o wysokiej wydajności — tych, którzy odmawiają przyjęcia do wiadomości mgły poznawczej po południu, spadków energii czy przedłużonej regeneracji jako nieuchronności. Każdy składnik dawkowany jest na klinicznie skutecznych poziomach, poparty badaniami peer-reviewed i produkowany według najwyższych standardów GMP. Żadnych zastrzeżonych mieszanek. Żadnego ukrywania za niejasnym dawkowaniem. Tylko precyzyjna suplementacja na długą grę.",
    price: "129,00 zł",
    originalPrice: "159,00 zł",
    img: "/images/products/studio-performance.png",
    hoverImg: "/images/website/hero-movement-woman.jpg",
    detailImg: "/images/website/store-performance-detail.jpg",
    accentImg: "/images/website/store-performance-accent.jpg",
    gallery: [
      "/images/website/perf-authentic-2.png",
      "/images/website/perf-authentic-6.png",
      "/images/website/perf-dynamic-fashion.png",
      "/images/website/perf-high-fashion-6.png",
      "/images/website/perf-minimalist-lifestyle.png",
      "/images/website/perf-real-product.png",
      "/images/website/perf-b-authentic-3.jpeg",
      "/images/website/perf-b-dynamic-14.jpeg",
    ],
    color: "#111111",
    colorLight: "rgba(17,17,17,0.06)",
    glow: "rgba(17,17,17,0.07)",
    index: "001",
    benefits: [
      "Trwała energia bez nerwowości i spadków",
      "Lepsza jasność umysłu i skupienie",
      "Przyspieszona regeneracja potreningowa",
      "Wspiera zdrowie mitochondriów",
    ],
    ingredients: [
      { name: "NMN", dose: "500mg", benefit: "Prekursor NAD+ dla komórkowej produkcji energii" },
      { name: "CoQ10", dose: "200mg", benefit: "Wydajność mitochondriów i ochrona antyoksydacyjna" },
      { name: "Alpha-GPC", dose: "300mg", benefit: "Prekursor choliny dla skupienia i pamięci" },
      { name: "Rhodiola Rosea", dose: "400mg", benefit: "Adaptogen dla odporności na stres i zmęczenie" },
      { name: "Witaminy z grupy B", dose: "Pełne spektrum", benefit: "Metabolizm energii i funkcje neurologiczne" },
    ],
    usage: "Przyjmuj 2 kapsułki z śniadaniem. Wchłanianie NMN jest znacząco wspomagane przez obecność tłuszczu w diecie, a poranne dawkowanie jest zgodne z naturalnym rytmem syntezy NAD+. CoQ10 jest rozpuszczalny w tłuszczach — jedzenie zwiększa biodostępność nawet 3-krotnie. Rhodiola najlepiej działa rano; jej łagodne działanie stymulujące na oś HPA może zakłócać zasypianie, jeśli jest przyjmowana po 14:00. Minimalne 8 tygodni regularnego stosowania jest wymagane, by zaobserwować mierzalne zmiany w metabolizmie energii i czasie regeneracji.",
    servings: "60 kapsułek / 30 porcji",
  },
  {
    slug: "balance",
    name: "Balance",
    fullName: "knowing more. Balance",
    tagline: "Kortyzol · Sen · Hormony",
    headline: "Harmonia\nod środka.",
    description: "Adaptogenne wsparcie dla wymagań nowoczesnego życia o wysokiej wydajności.",
    longDescription:
      "Balance adresuje to, co nowoczesne życie stale zakłóca: rytm kortyzolu, architekturę snu i równowagę hormonalną. Sformułowany wokół najdokładniej zbadanych związków adaptogennych, każdy dawkowany na dokładnym poziomie stosowanym w badaniach klinicznych. Niezależnie od tego, czy zarządzasz firmą, intensywnie trenujesz, czy po prostu poruszasz się w nieustannym tempie współczesnego życia — Balance to fundament, który pozwala wszystkiemu innemu działać.",
    price: "129,00 zł",
    originalPrice: "159,00 zł",
    img: "/images/products/studio-balance.png",
    hoverImg: "/images/website/store-balance-hover2.png",
    detailImg: "/images/website/store-balance-detail.jpg",
    accentImg: "/images/website/store-balance-accent.jpg",
    gallery: [
      "/images/website/bal-real-product-3.jpeg",
      "/images/website/bal-minimalist-5.jpeg",
      "/images/website/bal-high-fashion-12.jpeg",
      "/images/website/bal-high-fashion-7.jpeg",
      "/images/website/bal-high-fashion-3.jpeg",
      "/images/website/bal-editorial-4.jpeg",
    ],
    color: "#A0784A",
    colorLight: "rgba(160,120,74,0.07)",
    glow: "rgba(160,120,74,0.09)",
    index: "002",
    benefits: [
      "Reguluje kortyzol i odpowiedź na stres",
      "Poprawia jakość i strukturę snu",
      "Wspiera równowagę hormonalną",
      "Redukuje lęk i reaktywność emocjonalną",
    ],
    ingredients: [
      { name: "Ashwagandha KSM-66", dose: "600mg", benefit: "Klinicznie potwierdzona redukcja kortyzolu" },
      { name: "L-Teanina", dose: "200mg", benefit: "Spokojne skupienie bez sedacji" },
      { name: "Glicynian magnezu", dose: "400mg", benefit: "Jakość snu i rozluźnienie mięśni" },
      { name: "Fosfatydyloseryna", dose: "300mg", benefit: "Regulacja kortyzolu i wsparcie poznawcze" },
      { name: "Ekstrakt z melisy", dose: "500mg", benefit: "Redukcja lęku i ułatwienie zasypiania" },
    ],
    usage: "Przyjmuj 2 kapsułki 60–90 minut przed snem. Glicynian magnezu podnosi wewnątrzkomórkowy poziom magnezu wspierający aktywność receptorów GABA i rozluźnienie mięśni — oba najbardziej istotne w godzinach poprzedzających sen. Działanie obniżające kortyzol ashwagandhy jest kumulatywne i osiąga szczyt przy regularnym przyjmowaniu wieczorem, zgodnie z naturalnym spadkiem kortyzolu po 18:00. Fosfatydyloseryna tłumi skoki kortyzolu wywołane wysiłkiem; wieczorne dawkowanie pomaga zakończyć cykl eliminacji kortyzolu. L-teanina promuje aktywność fal alfa mózgu, ułatwiając przejście z czuwania w stan odpoczynku. Pozwól na 4–6 tygodni regularnego stosowania przed oceną zmian w jakości snu.",
    servings: "60 kapsułek / 30 porcji",
  },
  {
    slug: "gut-health",
    name: "Gut Health",
    fullName: "knowing more. Gut Health",
    tagline: "Mikrobiom · Trawienie · Odporność",
    headline: "Fundament\nwszystkiego.",
    description: "Precyzyjna formuła probiotyczna i prebiotyczna dla ogólnego dobrostanu.",
    longDescription:
      "Jelita to drugi mózg, siedziba odporności i źródło większości przewlekłych stanów zapalnych. Gut Health dostarcza kompleksową interwencję ekosystemową — 50 miliardów CFU starannie wyselekcjonowanych szczepów probiotycznych w połączeniu z substratem prebiotycznym zapewniającym przeżycie i kolonizację. L-glutamina wspiera integralność bariery jelitowej, podczas gdy kompleks enzymów trawiennych zapewnia pełne przyswajanie składników odżywczych z każdego posiłku. To nie jest zwykły probiotyk. To kompletna formuła architektury jelitowej.",
    price: "129,00 zł",
    originalPrice: "159,00 zł",
    img: "/images/products/studio-gut-health.png",
    hoverImg: "/images/website/store-gutHealth-hover2.png",
    detailImg: "/images/website/store-gutHealth-detail.jpg",
    accentImg: "/images/website/store-gutHealth-accent.jpg",
    gallery: [
      "/images/website/gut-editorial-3.jpeg",
      "/images/website/gut-minimalist.jpeg",
      "/images/website/gut-high-fashion-9.jpeg",
      "/images/website/gut-dynamic-13.jpeg",
      "/images/website/gut-dynamic-10.jpeg",
      "/images/website/gut-dynamic-8.jpeg",
      "/images/website/gut-a-dynamic-6.png",
      "/images/website/gut-a-artistic-3.png",
    ],
    color: "#C4682A",
    colorLight: "rgba(196,104,42,0.07)",
    glow: "rgba(196,104,42,0.09)",
    index: "003",
    benefits: [
      "50 mld CFU kompleks probiotyczny z wielu szczepów",
      "Wspiera integralność bariery jelitowej",
      "Wzmacnia funkcję układu odpornościowego",
      "Poprawia wchłanianie składników odżywczych",
    ],
    ingredients: [
      { name: "Probiotyk wieloszczepowy", dose: "50 mld CFU", benefit: "Różnorodność i odporność mikrobiomu" },
      { name: "Prebiotyk FOS/Inulina", dose: "3g", benefit: "Podłoże dla probiotyków i wsparcie kolonizacji" },
      { name: "L-Glutamina", dose: "2g", benefit: "Naprawa błony śluzowej jelit i integralność bariery" },
      { name: "Kompleks enzymów trawiennych", dose: "250mg", benefit: "Pełne trawienie makroskładników" },
      { name: "Cynk", dose: "15mg", benefit: "Bariera jelitowa i funkcja odpornościowa" },
    ],
    usage: "Przyjmuj 1 kapsułkę na czczo 20–30 minut przed śniadaniem. Błona śluzowa jelit jest najbardziej receptywna na L-glutaminę w stanie głodzenia — jedzenie wywołuje aktywność enzymów trawiennych, które mogą degradować suplementarną glutaminę przed dotarciem do błony śluzowej jelit. Szczepy probiotyczne kolonizują się najskuteczniej, gdy wydzielanie kwasu żołądkowego jest najniższe, co następuje w porannym oknie przed posiłkiem. Prebiotyczny FOS/inulina powoli fermentuje w jelicie grubym; poranne dawkowanie synchronizuje szczytową aktywność fermentacji z naturalnymi wzorcami cyrkadiańskiej motoryki jelit. Pozwól na 6–8 tygodni regularnego stosowania przed oceną zmian w mikrobiomie — tyle czasu potrzeba na znaczące zmiany w różnorodności drobnoustrojów. Przechowuj w lodówce po otwarciu, aby zachować żywotność CFU.",
    servings: "30 kapsułek / 30 porcji",
  },
];

export function getProductPL(slug: string): Product | undefined {
  return productsPL.find((p) => p.slug === slug);
}
